api = "0.7"

[buildpack]
  description = "A buildpack for installing and configuring GitHub CLI"
  homepage = "https://github.com/cli/cli"
  id = "paketo-buildpacks/github-cli"
  keywords = ["github", "cli", "gh"]
  name = "Paketo Buildpack for GitHub CLI"
  version = "0.1.0"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/github-cli/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*" 